#!/bin/bash
#SBATCH -A uot166
#SBATCH --job-name="diablo"
#SBATCH --output="run.log"
#SBATCH --partition=compute
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=128
#SBATCH --mem=249208M
#SBATCH --export=ALL
#SBATCH --time=30    # time limit in minutes

module purge
module load slurm cpu/0.17.3b  gcc/10.2.0/npcyll4 openmpi/4.1.3

SW=/expanse/lustre/projects/uot166/fegaras
export DIABLO_HOME=/home/$USER/TensorPlanner
export SCALA_HOME=$SW/scala-2.12.3
export SPARK_HOME=$SW/spark-3.1.2-bin-hadoop3.2

JARS=${DIABLO_HOME}/lib/diablo.jar
for I in core sql; do
    JARS=${JARS}:`ls ${SPARK_HOME}/jars/spark-${I}*.jar`
done
export JARS=${JARS}

export PATH="$SCALA_HOME/bin:$DIABLO_HOME/bin:$PATH"

file="mult.diablo"
echo compiling $file ...
diablo $file

ulimit -l unlimited
ulimit -s unlimited

export diablo_collect=false

SOCKETS=2

# for each expanse node: 2 sockets, 1 executor per socket, 64 threads per executor
mpirun -N $SOCKETS --bind-to socket a.out 20000 10
